Create 1_file
nikita-awasthi/bo-test-2 pull request #12
Opened 2022-05-23 14:15 UTC by nikita-awasthi

2022-05-23 14:18 UTC, jai-bo commented on file_2
> +file 2
comment 1

2022-05-23 14:19 UTC, jai-bo requested changes

2022-05-24 06:48 UTC, nikita-awasthi commented on initial_commit_file
> +initial commit before pull request
Some comment

2022-05-24 06:48 UTC, jai-bo commented on new_branch_1_commit_after_pr
> +after pr
Comment 1

2022-05-24 06:49 UTC, jai-bo requested changes

2022-05-24 06:49 UTC, jai-bo commented on new_branch_1_commit_after_pr
> +after pr
Comment 3 review

2022-05-24 06:49 UTC, nikita-awasthi commented on new_branch_1_commit_after_pr
> +after pr
owner nested comment

2022-05-24 06:49 UTC, nikita-awasthi commented on new_branch_1_commit_after_pr
> +after pr
owner nested comment

2022-05-24 06:58 UTC, jai-bo commented on new_branch_1_commit_after_pr
> +after pr
> owner nested comment

nested comment

2024-09-12 08:01 UTC, closed without merging

2024-09-12 08:01 UTC, nikita-awasthi commented
NA